### ISSUE TITLE
Sync from RR->TD

### ISSUE THREAD

**Issue by AndBerna** [kdnk/roamist#144]
## Why
I can not find in the documentation if there is any kind of automatic sync from RR to TD. What happens if I mark a task as completed in Roam?

## What

I can see from the documentation that RR can be updated with the `sync-completed

But I do not understand if it happens in the other way around.

As well, if I erase any task in RR or TD, does it disappear? I am worried I will end with two not sync todo lists

Thanks in advance

**Comment by kdnk** [comment]
@AndBerna Thanks for using this plugin!😄

> I can not find in the documentation if there is any kind of automatic sync from RR to TD. What happens if I mark a task as completed in Roam?
- What do you mean by `automatic sync`?
- It depends on your settings. If you have the following option (`Disable checkbox sync feature`) ~~enabled~~ disabled, turning `TODO` into `DONE` inside Roam Research would also change the status inside Todoist. Otherwise, nothing happens.
![CleanShot 2023-04-06 at 13 55 49](https://user-images.githubusercontent.com/15260226/230275559-3553eb22-aeec-461b-9728-7889da7da666.png)

> As well, if I erase any task in RR or TD, does it disappear? I am worried I will end with two not sync todo lists

- What do you mean by `disappear`?
- Roamist is a Roam Research plugin, so making changes within Todoist won't have any effect. You need to use `sync-completed` functionality or enable the `Disable checkbox sync feature` option **explicitly**.

If you have some concerns about using this plugin, I reccomend tyring it out with a new Todoist account and a new Roam Research's graph (like the video in the README.md).

**Comment by AndBerna** [comment]
@kdnk thanks for the quick and extensive answer

- By `automatic sync` I wanted to ask if the sync between Roam Research and Todoist could happen without needing to trigger the `sync-completed` button

- By `disappear` I wanted to ask if I erase one task in either Roam, what happens on Todoist?

-  I am not sure I understand the option `Disable checkbox sync feature`. Could you expand on it?

Thanks in advance 😄

**Comment by kdnk** [comment]
> By `automatic sync` I wanted to ask if the sync between Roam Research and Todoist could happen without needing to trigger the `sync-completed` button

No. You need to call `sync-completed` explicitly.

> By `disappear` I wanted to ask if I erase one task in either Roam, what happens on Todoist?

Basically, this plugin works only in one direction, from Todoist to Roam.
If you erase anything on Roam, nothing should happen on Todoist.

> I am not sure I understand the option `Disable checkbox sync feature`. Could you expand on it?

As I said, this plugin works Todoist → Roam. However, this plugin offers a functionality that allows completing tasks in Roam to be reflected in Todoist. (which is Roam → Todoist direction).
If you enable `Disable checkbox sync feature`, the functionality won't work.

**Comment by AndBerna** [comment]
Crystal clear!  All doubts solved 😄 . I will therefore close the issue. Thanks!
